//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.MileageHistory = new HashSet<MileageHistory>();
        }
    
        public int CarId { get; set; }
        public int BrandId { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> TransmissionId { get; set; }
        public Nullable<int> BodyId { get; set; }
        public string Plate { get; set; }
        public string VIN { get; set; }
        public int Year { get; set; }
        public int Avaiability { get; set; }
        public Nullable<int> Power { get; set; }
    
        public virtual Brands Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MileageHistory> MileageHistory { get; set; }
        public virtual Models Models { get; set; }
        public virtual Transmissions Transmissions { get; set; }
    }
}
