//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int RentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime Length { get; set; }
        public double DiscountValue { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
